"""BCU reference tool menu + our coverage — drives the dashboard's Map tab for BCU.

Extracted from ``references/reference_tool_master_menu.md`` (AI-processed reference tool emulator
reading; newer product but same menu structure). The order = reference tool order
(important for byte/bit mapping). Everything "todo" until we have sniffed the BCU. `ref` = hints from
the doc's analysis notes. Prioritised for a BCU sniff: **EKA option, Market, Daytime
run lights, immobiliser** (see ``references/bcu_sniff_plan.md`` + ``bcu_key_coding.md``).
status: ok (confirmed) / maybe (likely) / todo. Update here after every sniff.
"""

BCU_MENU = [
    {"cat": "DCU Read Inputs — LIGHTS", "items": [
        {"name": "Side lights", "status": "todo", "ref": ""},
        {"name": "Main beam", "status": "todo", "ref": ""},
        {"name": "Dipped", "status": "todo", "ref": ""},
        {"name": "Front fog light", "status": "todo", "ref": ""},
        {"name": "Rear fog light", "status": "todo", "ref": ""},
        {"name": "Left indicator", "status": "todo", "ref": ""},
        {"name": "Right indicator", "status": "todo", "ref": ""},
        {"name": "Hazard", "status": "todo", "ref": ""},
        {"name": "Daytime run light", "status": "todo", "ref": ""},
    ]},
    {"cat": "DCU Read Inputs — DOORS / BODY INPUTS", "items": [
        {"name": "Passenger door switch", "status": "todo", "ref": ""},
        {"name": "Driver door switch", "status": "todo", "ref": ""},
        {"name": "Bonnet", "status": "todo", "ref": ""},
        {"name": "Key lock", "status": "todo", "ref": ""},
        {"name": "Key unlock", "status": "todo", "ref": ""},
        {"name": "CDL Lock", "status": "todo", "ref": ""},
        {"name": "CDL unlock", "status": "todo", "ref": ""},
        {"name": "Inertia", "status": "todo", "ref": "verify live vs latched vs polarity"},
        {"name": "Ignition key inserted", "status": "todo", "ref": ""},
        {"name": "Transfer box neutral", "status": "todo", "ref": "distinct from Transfer neutral switch"},
        {"name": "Park/neutral", "status": "todo", "ref": "distinct from Park neutral switch"},
    ]},
    {"cat": "DCU Read Inputs — TRANSMISSION", "items": [
        {"name": "Reverse idle", "status": "todo", "ref": ""},
        {"name": "Transfer neutral switch", "status": "todo", "ref": ""},
        {"name": "Autobox W switch", "status": "todo", "ref": ""},
        {"name": "Autobox X switch", "status": "todo", "ref": ""},
        {"name": "Autobox Y switch", "status": "todo", "ref": ""},
        {"name": "Autobox Z switch", "status": "todo", "ref": ""},
        {"name": "Park neutral switch", "status": "todo", "ref": ""},
    ]},
    {"cat": "DCU Read Inputs — WINDOWS", "items": [
        {"name": "Front LEFT down", "status": "todo", "ref": ""},
        {"name": "Front LEFT up", "status": "todo", "ref": ""},
        {"name": "Front RIGHT down", "status": "todo", "ref": ""},
        {"name": "Front RIGHT up", "status": "todo", "ref": ""},
    ]},
    {"cat": "DCU Read Inputs — WASH WIPE", "items": [
        {"name": "Front intermit", "status": "todo", "ref": ""},
        {"name": "Front wash", "status": "todo", "ref": ""},
        {"name": "Front wiper parked", "status": "todo", "ref": ""},
        {"name": "Front wiper speed", "status": "todo", "ref": "numeric; likely multi-bit/byte"},
        {"name": "Rear wiper", "status": "todo", "ref": ""},
        {"name": "Rear wash", "status": "todo", "ref": ""},
    ]},
    {"cat": "DCU Read Inputs — HEATED SCREEN / ENGINE STATE", "items": [
        {"name": "Heated screen switch", "status": "todo", "ref": ""},
        {"name": "Ignition 2", "status": "todo", "ref": ""},
        {"name": "Engine speed signal", "status": "todo", "ref": ""},
    ]},
    {"cat": "BCU Instruments — DISCRETE INPUTS / WARNING STATES", "items": [
        {"name": "LH DI", "status": "todo", "ref": ""},
        {"name": "RH DI", "status": "todo", "ref": ""},
        {"name": "LH Tailor DI", "status": "todo", "ref": ""},
        {"name": "RH Tailor DI", "status": "todo", "ref": ""},
        {"name": "Seat belt", "status": "todo", "ref": ""},
        {"name": "Diff lock", "status": "todo", "ref": ""},
        {"name": "Transfer neutral", "status": "todo", "ref": ""},
        {"name": "Autobox manual", "status": "todo", "ref": ""},
        {"name": "Autobox sport", "status": "todo", "ref": ""},
        {"name": "Offroad level", "status": "todo", "ref": ""},
        {"name": "ABS", "status": "todo", "ref": "warning lamp, not switch"},
        {"name": "Traction control", "status": "todo", "ref": ""},
        {"name": "SRS", "status": "todo", "ref": "warning lamp"},
        {"name": "HDC select", "status": "todo", "ref": ""},
        {"name": "Glow plug", "status": "todo", "ref": ""},
        {"name": "Brake", "status": "todo", "ref": ""},
        {"name": "Oil pressure", "status": "todo", "ref": ""},
        {"name": "Alternator", "status": "todo", "ref": ""},
        {"name": "Check engine", "status": "todo", "ref": "warning lamp"},
        {"name": "Fuel filter", "status": "todo", "ref": ""},
        {"name": "Transmission temp.", "status": "todo", "ref": ""},
        {"name": "Check ACE", "status": "todo", "ref": "warning lamp"},
        {"name": "Check HDC", "status": "todo", "ref": "warning lamp"},
        {"name": "Check SLS", "status": "todo", "ref": "warning lamp"},
    ]},
    {"cat": "BCU Instruments — MILEAGE / TRIP", "items": [
        {"name": "Instr. milage (km)", "status": "todo", "ref": "instr-pack odometer reading; byte order/scale"},
        {"name": "BCU milage (km)", "status": "todo", "ref": "BCU-stored odometer reading; byte order/scale"},
        {"name": "IP trip switch", "status": "todo", "ref": ""},
    ]},
    {"cat": "BCU Power distribution — IGNITION / SUPPLY", "items": [
        {"name": "BCU ignition pos. 1", "status": "todo", "ref": "bitfield candidate (pos 1/2/3)"},
        {"name": "BCU ignition pos. 2", "status": "todo", "ref": "bitfield candidate (pos 1/2/3)"},
        {"name": "BCU ignition pos. 3", "status": "todo", "ref": "bitfield candidate (pos 1/2/3)"},
        {"name": "IP ignition pos. 2", "status": "todo", "ref": "instrument-pack report"},
        {"name": "IDM ignition pos. 2", "status": "todo", "ref": "IDM report"},
        {"name": "IDM battery (V)", "status": "todo", "ref": "voltage; scale TBD"},
        {"name": "BCU switch power", "status": "todo", "ref": "voltage; scale TBD"},
        {"name": "BCU relay power", "status": "todo", "ref": "voltage; scale TBD"},
    ]},
    {"cat": "BCU Settings — LIGHTS-WINDOWS-SEATS", "items": [
        {"name": "Front fog lamp", "status": "todo", "ref": ""},
        {"name": "Daytime run lights", "status": "todo", "ref": "★ enum NONE/NO MAIN/NO HEADS"},
        {"name": "Courtest head lamps", "status": "todo", "ref": ""},
        {"name": "Headlamp power wash", "status": "todo", "ref": ""},
        {"name": "Electric window front", "status": "todo", "ref": ""},
        {"name": "Rear windows sunroof", "status": "todo", "ref": ""},
        {"name": "Heated front screen", "status": "todo", "ref": ""},
        {"name": "Electric front seats", "status": "todo", "ref": ""},
        {"name": "Programmed wash wip", "status": "todo", "ref": "enum, not boolean"},
        {"name": "Seat belt warning", "status": "todo", "ref": "enum (TIMED/…)"},
        {"name": "Seat belt warning soun", "status": "todo", "ref": ""},
        {"name": "Autographics", "status": "todo", "ref": ""},
    ]},
    {"cat": "BCU Settings — TRANSM-LOCK-WARN", "items": [
        {"name": "Transmission", "status": "todo", "ref": "enum (AUTO/…)"},
        {"name": "Shift Interlock", "status": "todo", "ref": ""},
        {"name": "HDC", "status": "todo", "ref": ""},
        {"name": "Superlock", "status": "todo", "ref": ""},
        {"name": "Single point entry", "status": "todo", "ref": ""},
        {"name": "Speed lock option", "status": "todo", "ref": ""},
        {"name": "Mislock option", "status": "todo", "ref": ""},
        {"name": "Bathrobe lock option", "status": "todo", "ref": ""},
        {"name": "Odometer error warn", "status": "todo", "ref": ""},
        {"name": "Key warning", "status": "todo", "ref": ""},
        {"name": "Low battery warning", "status": "todo", "ref": ""},
        {"name": "Bulb failure", "status": "todo", "ref": ""},
    ]},
    {"cat": "BCU Settings — INSTRUMENT PACK", "items": [
        {"name": "Transmission", "status": "todo", "ref": "vehicle config"},
        {"name": "Engine", "status": "todo", "ref": "enum (PETROL/…)"},
        {"name": "ACE", "status": "todo", "ref": "feature flag"},
        {"name": "SLS", "status": "todo", "ref": "feature flag"},
        {"name": "Gulf", "status": "todo", "ref": "feature flag"},
        {"name": "Police", "status": "todo", "ref": "feature flag"},
        {"name": "HDC", "status": "todo", "ref": "feature flag"},
        {"name": "TRC", "status": "todo", "ref": "feature flag"},
    ]},
    {"cat": "BCU Settings — ALARM-OTHER", "items": [
        {"name": "Alarm", "status": "todo", "ref": ""},
        {"name": "Alarm option", "status": "todo", "ref": ""},
        {"name": "Alarm disarm", "status": "todo", "ref": "enum field"},
        {"name": "Alarm sounder", "status": "todo", "ref": "enum field"},
        {"name": "Alarm tamper", "status": "todo", "ref": ""},
        {"name": "Engine immobil.", "status": "todo", "ref": "★ enum (LED OFF/…)"},
        {"name": "Passive immobil.", "status": "todo", "ref": "★ en/dis"},
        {"name": "Inertia switch", "status": "todo", "ref": "enum (NO HAZARD/…)"},
        {"name": "Hazard option", "status": "todo", "ref": "enum field"},
        {"name": "Volumetric sensor", "status": "todo", "ref": ""},
        {"name": "Market", "status": "todo", "ref": "★ enum; market code not mapped (controls DRL etc.)"},
        {"name": "EKA option", "status": "todo", "ref": "★ en/dis; linked to the EKA code utility"},
        {"name": "EKA code (read/write)", "status": "maybe", "ref": "PROVEN: read 21 CC, write 3B CC <4B>. RDL 016 = XXXX (3b cc XX XX XX XX). ⚠️ never write blindly"},
        {"name": "BCU settings IDs", "status": "maybe", "ref": "auto-extracted: 21 C6/C7/CA/CB/D3/D4-D7/EB (match against settings groups)"},
        {"name": "Cruise control", "status": "todo", "ref": ""},
        {"name": "Air conditioning", "status": "todo", "ref": ""},
        {"name": "Fuel burning heater", "status": "todo", "ref": ""},
        {"name": "Passive coil", "status": "todo", "ref": ""},
        {"name": "Transit mode", "status": "todo", "ref": ""},
    ]},
    {"cat": "BCU Outputs — BODY", "items": [
        {"name": "Front fog lights", "status": "todo", "ref": ""},
        {"name": "Rear fog lights", "status": "todo", "ref": ""},
        {"name": "Daytime running lights", "status": "todo", "ref": ""},
        {"name": "LH indicator enable", "status": "todo", "ref": "seq 4; UI shows the label twice"},
        {"name": "LH indicator enable (2)", "status": "todo", "ref": "seq 5; may turn out to be RH"},
        {"name": "Front left window up", "status": "todo", "ref": ""},
        {"name": "Front left window down", "status": "todo", "ref": ""},
        {"name": "Front right window up", "status": "todo", "ref": ""},
        {"name": "Front right window down", "status": "todo", "ref": "UI-truncated label"},
        {"name": "Rear windows enable", "status": "todo", "ref": ""},
        {"name": "Sunroof enable", "status": "todo", "ref": ""},
        {"name": "Front wiper enable", "status": "todo", "ref": ""},
        {"name": "Tail wiper enable", "status": "todo", "ref": ""},
        {"name": "Head lamp power wash", "status": "todo", "ref": ""},
        {"name": "Heated screen", "status": "todo", "ref": ""},
        {"name": "Heat. rear screen lamp", "status": "todo", "ref": ""},
        {"name": "Check engine lamp", "status": "todo", "ref": ""},
    ]},
    {"cat": "BCU Outputs — SECURITY/LOCKING", "items": [
        {"name": "Horn", "status": "todo", "ref": ""},
        {"name": "BBUS ALL", "status": "todo", "ref": ""},
        {"name": "BBUS ST", "status": "todo", "ref": ""},
        {"name": "Fuel flap", "status": "todo", "ref": ""},
        {"name": "Alarm LED", "status": "todo", "ref": ""},
        {"name": "Ignition interlock", "status": "todo", "ref": ""},
        {"name": "Crank Enable", "status": "todo", "ref": ""},
        {"name": "Volumetric power", "status": "todo", "ref": ""},
        {"name": "Robust immo.", "status": "todo", "ref": ""},
        {"name": "Transponder Power", "status": "todo", "ref": ""},
        {"name": "Lock", "status": "todo", "ref": ""},
        {"name": "Unlock", "status": "todo", "ref": ""},
        {"name": "Superlock", "status": "todo", "ref": ""},
        {"name": "Single point entry", "status": "todo", "ref": ""},
    ]},
]
